db:
  host: localhost
  port: 5432
  user: postgres
  password: pass1234
  database: rinha_backend
  defaultMaxConns: 8

server:
  port: "9090"
  rateLimiting:
    enable: true
    rate: 100
    tokenBurst: 50
